package mods.eln.client.render;

import mods.eln.Eln;
import mods.eln.compat.BlockMeta;
import mods.eln.compat.IItemRenderer;
import mods.eln.generic.GenericItemBlockUsingDamage;
import mods.eln.generic.GenericItemBlockUsingDamageDescriptor;
import mods.eln.generic.GenericItemUsingDamage;
import mods.eln.generic.GenericItemUsingDamageDescriptor;
import net.minecraft.block.Block;
import net.minecraft.client.renderer.block.model.IBakedModel;
import net.minecraft.client.renderer.block.model.ModelResourceLocation;
import net.minecraft.client.renderer.block.statemap.StateMap;
import net.minecraft.item.Item;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.client.event.ModelBakeEvent;
import net.minecraftforge.client.event.ModelRegistryEvent;
import net.minecraftforge.client.model.ModelLoader;
import net.minecraftforge.fml.common.eventhandler.SubscribeEvent;
import net.minecraftforge.fml.common.registry.ForgeRegistries;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

import java.util.HashMap;
import java.util.Map;

/**
 * Client model registration for EA's items and INVISIBLE blocks (1.12 port, WP5). Registered on the Forge bus in
 * ClientProxy.preInit (ModelRegistryEvent/ModelBakeEvent fire between preInit and init).
 *
 * Damage-indexed "mega" items (six/transparent node items, shared items) all map to one model per item,
 * models/item/&lt;registry name&gt;.json (parent builtin/entity). On bake, it is replaced by an {@link ItemBridgeModel}
 * that, per stack and per render type, either hands the stack to {@link ItemBridgeRenderer} (the descriptor's
 * 1.7.10 IItemRenderer code) or falls back to the flat icon of the descriptor's 1.7.10 icon name
 * (models/item/icon/{items,blocks}/&lt;icon&gt;.json, generated by eln/tools/gen-item-models.py).
 * Other EA items use models/item/&lt;registry name&gt;.json.
 */
@SideOnly(Side.CLIENT)
public final class ElnItemModels {
    /** Per bridged item: damage -> icon model location (only icons whose JSON exists). */
    private final Map<Item, Map<Integer, ModelResourceLocation>> iconLocations = new HashMap<>();

    static ModelResourceLocation bridgeLocation(Item item) {
        return new ModelResourceLocation(item.getRegistryName(), "inventory");
    }

    private static boolean isBridged(Item item) {
        return item instanceof IItemRenderer || item instanceof GenericItemUsingDamage || item instanceof GenericItemBlockUsingDamage;
    }

    /** "eln:foo" icon name -> eln:icon/&lt;kind&gt;/foo#inventory, or null when there is no such texture/model. */
    private static ModelResourceLocation iconLocation(String iconName, String kind) {
        if (iconName == null) return null;
        String name = iconName.startsWith("eln:") ? iconName.substring(4) : iconName;
        name = name.toLowerCase(java.util.Locale.ROOT);
        String json = "assets/eln/models/item/icon/" + kind + "/" + name + ".json";
        if (ElnItemModels.class.getClassLoader().getResource(json) == null) return null;
        return new ModelResourceLocation(new ResourceLocation(Eln.MODID, "icon/" + kind + "/" + name), "inventory");
    }

    @SubscribeEvent
    public void onModelRegistry(ModelRegistryEvent event) {
        for (Item item : ForgeRegistries.ITEMS) {
            ResourceLocation id = item.getRegistryName();
            if (id == null || !Eln.MODID.equals(id.getNamespace())) continue;
            if (!isBridged(item)) {
                ModelLoader.setCustomModelResourceLocation(item, 0, new ModelResourceLocation(id, "inventory"));
                continue;
            }
            final ModelResourceLocation bridge = bridgeLocation(item);
            ModelLoader.setCustomMeshDefinition(item, stack -> bridge);
            ModelLoader.registerItemVariants(item, bridge);
            item.setTileEntityItemStackRenderer(ItemBridgeRenderer.INSTANCE);

            Map<Integer, ModelResourceLocation> icons = new HashMap<>();
            if (item instanceof GenericItemUsingDamage) {
                for (Map.Entry<Integer, ?> e : ((GenericItemUsingDamage<?>) item).subItemList.entrySet()) {
                    GenericItemUsingDamageDescriptor d = (GenericItemUsingDamageDescriptor) e.getValue();
                    ModelResourceLocation icon = iconLocation(d.getIconName(), "items");
                    if (icon != null) icons.put(e.getKey(), icon);
                }
            } else if (item instanceof GenericItemBlockUsingDamage) {
                for (Map.Entry<Integer, ?> e : ((GenericItemBlockUsingDamage<?>) item).subItemList.entrySet()) {
                    GenericItemBlockUsingDamageDescriptor d = (GenericItemBlockUsingDamageDescriptor) e.getValue();
                    ModelResourceLocation icon = iconLocation(d.getIconName(), "blocks");
                    if (icon != null) icons.put(e.getKey(), icon);
                }
            }
            for (ModelResourceLocation icon : icons.values()) ModelLoader.registerItemVariants(item, icon);
            iconLocations.put(item, icons);
        }

        // INVISIBLE blocks (TESR / no model): one "normal" variant with a particle-only model (break particles).
        StateMap ignoreMeta = new StateMap.Builder().ignore(BlockMeta.META).build();
        for (Block block : ForgeRegistries.BLOCKS) {
            ResourceLocation id = block.getRegistryName();
            if (id == null || !Eln.MODID.equals(id.getNamespace())) continue;
            if (block.getBlockState().getProperties().contains(BlockMeta.META)) {
                ModelLoader.setCustomStateMapper(block, ignoreMeta);
            }
        }
    }

    @SubscribeEvent
    public void onModelBake(ModelBakeEvent event) {
        for (Map.Entry<Item, Map<Integer, ModelResourceLocation>> e : iconLocations.entrySet()) {
            ModelResourceLocation bridge = bridgeLocation(e.getKey());
            IBakedModel base = event.getModelRegistry().getObject(bridge);
            Map<Integer, IBakedModel> icons = new HashMap<>();
            for (Map.Entry<Integer, ModelResourceLocation> icon : e.getValue().entrySet()) {
                IBakedModel m = event.getModelRegistry().getObject(icon.getValue());
                if (m != null) icons.put(icon.getKey(), m);
            }
            event.getModelRegistry().putObject(bridge, new ItemBridgeModel(base, icons));
        }
    }
}
